version: '2'
services:
  mysql:
    image: mysql/mysql-server:5.6
    ports:
     - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mail2rails
      MYSQL_USER: mail2rails
      MYSQL_PASSWORD: mail2rails
  web:
    build: .
    environment:
      MYSQL_DATABASE: mail2rails
      MYSQL_USER: mail2rails
      MYSQL_PASSWORD: mail2rails      
    command: bash -c "bundle install ; sleep 10 ; RAILS_ENV=development rake db:migrate ; bundle exec rails s -e development -p 3000 -b '0.0.0.0'"
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  smtp:
    build: .
    environment:
      MYSQL_DATABASE: mail2rails
      MYSQL_USER: mail2rails
      MYSQL_PASSWORD: mail2rails    
    command: bash -c "bundle install ; bundle exec rails runner -e development bin/smtp_server.rb"
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "25:25"
    depends_on:
      - web
      - mysql
